version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_SITE_URL: ${NEXT_PUBLIC_SITE_URL:-http://localhost:3000}
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_SITE_URL=${NEXT_PUBLIC_SITE_URL:-http://localhost:3000}
      - CMC_API_KEY=${CMC_API_KEY}
      - RWA_API_KEY=${RWA_API_KEY}
    restart: unless-stopped
    # healthcheck:
    #   test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/api/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1); })"]
    #   interval: 30s
    #   timeout: 3s
    #   start_period: 40s
    #   retries: 3
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

# Optional: Add volume for persistent data if needed in the future
# volumes:
#   app-data: