name: 🐛 Bug Report
description: Create a report to help us improve
title: "[Bug]: "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible to help us resolve the issue quickly.

  - type: checkboxes
    id: terms
    attributes:
      label: Pre-flight checklist
      description: Please check all the following items before submitting this issue.
      options:
        - label: I have searched existing issues to ensure this bug hasn't been reported before
          required: true
        - label: I have checked the documentation and troubleshooting guides
          required: true
        - label: I am using the latest version of the application
          required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: What version of OnAptos are you running?
      placeholder: e.g., v1.0.0, main branch, commit hash
    validations:
      required: true

  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Chrome
        - Firefox
        - Safari
        - Microsoft Edge
        - Mobile Safari (iOS)
        - Chrome Mobile (Android)
        - Other

  - type: input
    id: operating-system
    attributes:
      label: Operating System
      description: What operating system are you using?
      placeholder: e.g., Windows 11, macOS 14, Ubuntu 22.04
    validations:
      required: true

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: |
        Provide a clear and concise description of what the bug is.
        
        **Tip**: You can attach images or videos by clicking this area to highlight it and then dragging files in.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: What did you expect to happen instead?
      placeholder: Describe what you expected...
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: |
        Please provide detailed steps to reproduce the issue.
        
        **Example:**
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
      placeholder: |
        1. 
        2. 
        3. 
        ...
    validations:
      required: true

  - type: textarea
    id: console-errors
    attributes:
      label: Console errors
      description: |
        Please check the browser console (F12 → Console) and paste any error messages here.
        
        **Tip**: Use three backticks (```) to format code blocks.
      placeholder: |
        ```
        Paste console errors here...
        ```

  - type: textarea
    id: network-errors
    attributes:
      label: Network errors
      description: |
        Please check the browser Network tab (F12 → Network) for any failed requests and paste relevant information here.
      placeholder: |
        Failed requests:
        - URL: /api/...
        - Status: 500
        - Error: ...

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: |
        Add any other context about the problem here, such as:
        - Screenshots or videos
        - Configuration details
        - Related issues
        - Workarounds you've tried
      placeholder: Any additional information that might be helpful...

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Critical - Application is unusable
        - High - Major functionality is broken
        - Medium - Some functionality is impacted
        - Low - Minor issue or cosmetic problem
    validations:
      required: true

  - type: checkboxes
    id: volunteer
    attributes:
      label: Contribution
      description: Would you be interested in contributing a fix for this issue?
      options:
        - label: I would be willing to submit a PR to fix this issue